MAP_FRAME: '/map'
NODE:
    - id: 0
      type: 'intersection'
      point:
           x: 0.000000
           y: 0.000000
      label: ''
    - id: 1
      type: 'intersection'
      point:
           x: 7.250000
           y: 0.000000
      label: ''
    - id: 2
      type: 'intersection'
      point:
           x: 7.250000
           y: 16.599998
      label: ''
    - id: 3
      type: 'intersection'
      point:
           x: 0.000000
           y: 16.599998
      label: ''
    - id: 4
      type: 'intersection'
      point:
           x: -7.250000
           y: 16.599998
      label: ''
    - id: 5
      type: 'intersection'
      point:
           x: -7.250000
           y: 0.000000
      label: ''
    - id: 6
      type: 'intersection'
      point:
           x: -7.250000
           y: -16.599998
      label: ''
    - id: 7
      type: 'intersection'
      point:
           x: 0.000000
           y: -16.599998
      label: ''
    - id: 8
      type: 'intersection'
      point:
           x: 7.250000
           y: -16.599998
      label: ''
    - id: 9
      type: 'intersection'
      point:
           x: 7.250000
           y: 21.599998
      label: ''
    - id: 10
      type: 'intersection'
      point:
           x: 0.000000
           y: 21.599998
      label: ''
    - id: 11
      type: 'intersection'
      point:
           x: -7.250000
           y: 21.599998
      label: ''
    - id: 12
      type: 'intersection'
      point:
           x: -7.250000
           y: -20.000000
      label: ''
    - id: 13
      type: 'intersection'
      point:
           x: 0.000000
           y: -20.000000
      label: ''
    - id: 14
      type: 'intersection'
      point:
           x: 7.250000
           y: -20.000000
      label: ''
EDGE:
    - node_id: [0, 1]
    - node_id: [0, 3]
    - node_id: [0, 5]
    - node_id: [0, 7]
    - node_id: [1, 0]
    - node_id: [1, 2]
    - node_id: [1, 8]
    - node_id: [2, 1]
    - node_id: [2, 3]
    - node_id: [3, 0]
    - node_id: [3, 2]
    - node_id: [3, 4]
    - node_id: [4, 3]
    - node_id: [4, 5]
    - node_id: [5, 0]
    - node_id: [5, 4]
    - node_id: [5, 6]
    - node_id: [6, 5]
    - node_id: [6, 7]
    - node_id: [7, 0]
    - node_id: [7, 6]
    - node_id: [7, 8]
    - node_id: [8, 1]
    - node_id: [8, 7]
    - node_id: [9, 2]
    - node_id: [10, 3]
    - node_id: [11, 4]
    - node_id: [12, 6]
    - node_id: [13, 7]
    - node_id: [14, 8]
