MAP_FRAME: /map
NODE:
- id: 0
  type: intersection
  point:
    x: 2.818
    y: -6.97
  label: ''
- id: 1
  type: intersection
  point:
    x: 12.449
    y: -6.894
  label: ''
- id: 2
  type: intersection
  point:
    x: 20.111
    y: -6.144
  label: ''
- id: 3
  type: intersection
  point:
    x: 19.791
    y: 0.369
  label: ''
- id: 4
  type: intersection
  point:
    x: 12.902
    y: 0.47
  label: ''
- id: 5
  type: intersection
  point:
    x: 3.141
    y: -0.114
  label: ''
- id: 6
  type: intersection
  point:
    x: -5.923
    y: -0.235
  label: ''
- id: 7
  type: intersection
  point:
    x: -12.728
    y: -0.727
  label: ''
- id: 8
  type: intersection
  point:
    x: -13.246
    y: -7.301
  label: ''
- id: 9
  type: intersection
  point:
    x: -12.815
    y: -14.246
  label: ''
- id: 10
  type: intersection
  point:
    x: -6.3
    y: -14.438
  label: ''
- id: 11
  type: intersection
  point:
    x: 3.088
    y: -13.759
  label: ''
- id: 12
  type: intersection
  point:
    x: 12.778
    y: -13.524
  label: ''
- id: 13
  type: intersection
  point:
    x: 19.9
    y: -12.732
  label: ''
- id: 14
  type: intersection
  point:
    x: -6.764
    y: -7.358
  label: ''
EDGE:
- node_id:
  - 0
  - 1
- node_id:
  - 0
  - 3
- node_id:
  - 0
  - 5
- node_id:
  - 0
  - 7
- node_id:
  - 1
  - 0
- node_id:
  - 1
  - 2
- node_id:
  - 1
  - 8
- node_id:
  - 2
  - 1
- node_id:
  - 2
  - 3
- node_id:
  - 3
  - 0
- node_id:
  - 3
  - 2
- node_id:
  - 3
  - 4
- node_id:
  - 4
  - 3
- node_id:
  - 4
  - 5
- node_id:
  - 5
  - 0
- node_id:
  - 5
  - 4
- node_id:
  - 5
  - 6
- node_id:
  - 6
  - 5
- node_id:
  - 6
  - 7
- node_id:
  - 7
  - 0
- node_id:
  - 7
  - 6
- node_id:
  - 7
  - 8
- node_id:
  - 8
  - 1
- node_id:
  - 8
  - 7
- node_id:
  - 9
  - 2
- node_id:
  - 10
  - 3
- node_id:
  - 11
  - 4
- node_id:
  - 12
  - 6
- node_id:
  - 13
  - 7
- node_id:
  - 14
  - 8
